### ISSUE TITLE
Geen melding van het partitienummer in beschrijving Kadastraal Patrimoniumperceel

### ISSUE THREAD

**Issue by ddvlanck** [Informatievlaanderen/OSLOthema-perceel#1]
Waarom wordt in de beschrijving van Kadastraal Patrimoniumperceel geen melding gemaakt van het partitienummer?

De mogelijkheid bestaat dat gebruikers die met kadastrale info werken op zoek gaan naar **partitienummer** in dit applicatieprofiel en het niet vinden. Bijgevolg zullen ze veronderstellen dat dit niet meegenomen is in de oefening en dit dan ook niet gebruiken.

Ook met een voorbeeld duiden (PATKEY= CAPAKEY+partitienummer)

**Comment by KevinHaleydt** [comment]
Hi Dwight,

We zullen dit mee opnemen in de subtitel 'gebruik' van Kadastraal Patrimonionperceel.

To do:
(PATKEY= CAPAKEY+partitienummer) toevoegen in 'gebruik' van kadastraal Patrimoniumperceel

Kevin

**Comment by mvanbrab** [comment]
De voorgestelde oplossing/aanpassing is vanaf nu zichtbaar in de specificaties:
* https://otl-test.data.vlaanderen.be/doc/vocabularium/perceel/tijdens-aanpassingen-kandidaat-standaard
* https://otl-test.data.vlaanderen.be/doc/applicatieprofiel/perceel/tijdens-aanpassingen-kandidaat-standaard
* https://otl-test.data.vlaanderen.be/doc/vocabularium/bedrijventerrein/tijdens-aanpassingen-kandidaat-standaard
* https://otl-test.data.vlaanderen.be/doc/applicatieprofiel/bedrijventerrein/tijdens-aanpassingen-kandidaat-standaard

**Comment by bertvannuffelen** [comment]
opgenomen in specificatie
