### ISSUE TITLE
Eigenschap identificator mappen op http://www.w3.org/ns/adms#identifier 

### ISSUE THREAD

**Issue by mvanbrab** [Informatievlaanderen/OSLOthema-perceel#10]
Naar analogie met OSLO-Generiek::Object.identificator.

**Comment by mvanbrab** [comment]
Issue geldt voor
OSLO-Perceel:RuimtelijkeEenheid.identificator,
OSLO-Perceel.KadastraalPatrimoniumperceel.identficator,
en ook voor
OSLO-Bedrijventerrein::Plan.identificator

**Comment by mvanbrab** [comment]
De voorgestelde oplossing/aanpassing is vanaf nu zichtbaar in de specificaties:
* https://otl-test.data.vlaanderen.be/doc/vocabularium/perceel/tijdens-aanpassingen-kandidaat-standaard
* https://otl-test.data.vlaanderen.be/doc/applicatieprofiel/perceel/tijdens-aanpassingen-kandidaat-standaard
* https://otl-test.data.vlaanderen.be/doc/vocabularium/bedrijventerrein/tijdens-aanpassingen-kandidaat-standaard
* https://otl-test.data.vlaanderen.be/doc/applicatieprofiel/bedrijventerrein/tijdens-aanpassingen-kandidaat-standaard

**Comment by bertvannuffelen** [comment]
opgenomen in specificatie
