### ISSUE TITLE
RuimtelijkeEenheid en KadastraalPatrimoniumperceel afleiden van OSLO-Generiek::Object

### ISSUE THREAD

**Issue by mvanbrab** [Informatievlaanderen/OSLOthema-perceel#11]
Zoals ook OSLO-Perceel::Perceel dat voorheen was, zie #9 .
Dan is meteen ook #10 opgelost (op vocabularium niveau: niet meer nodig; op applicatieprofiel niveau: overerven met de daar gesuggereerde uri, zie de uri van identificator in OSLO-Generiek::Object.

**Comment by mvanbrab** [comment]
Zelfde bedenking voor OSLO-Bedrijventerrrein::Plan?

**Comment by GeertThijs** [comment]
Superklasse Object wordt doorgaans gebruikt om Objecten uit officiële registers aan te duiden. Ruimtelijke eenheden zijn soms maar niet altijd deel ve officiëel register. KadasraalPatrimoniumPercelen in principe is wel iets officieel (Kadastrale Legger!).

**Comment by mvanbrab** [comment]
Uiteindelijk dus enkel op Kadastraal Patrimoniumperceel toegepast; resulterende update zichtbaar op
* https://otl-test.data.vlaanderen.be/doc/vocabularium/perceel/tijdens-aanpassingen-kandidaat-standaard
* https://otl-test.data.vlaanderen.be/doc/vocabularium/bedrijventerrein/tijdens-aanpassingen-kandidaat-standaard

**Comment by bertvannuffelen** [comment]
opgenomen in specificatie
