### ISSUE TITLE
Stakeholders ontbreken in de specificaties

### ISSUE THREAD

**Issue by mvanbrab** [Informatievlaanderen/OSLOthema-perceel#12]
Ik heb een lijst met stakeholders gevonden, toegevoegd door Kevin.

**Comment by mvanbrab** [comment]
Het resultaat na activering van deze stakeholders lijst is vanaf nu zichtbaar in de specificaties:
* https://otl-test.data.vlaanderen.be/doc/vocabularium/perceel/tijdens-aanpassingen-kandidaat-standaard
* https://otl-test.data.vlaanderen.be/doc/applicatieprofiel/perceel/tijdens-aanpassingen-kandidaat-standaard
* https://otl-test.data.vlaanderen.be/doc/vocabularium/bedrijventerrein/tijdens-aanpassingen-kandidaat-standaard
* https://otl-test.data.vlaanderen.be/doc/applicatieprofiel/bedrijventerrein/tijdens-aanpassingen-kandidaat-standaard

**Comment by bertvannuffelen** [comment]
opgenomen in specificatie
