### ISSUE TITLE
Richting "is deel van" tussen Ontwikkelbare Bedrijvenzone en Bedrijventerrein?

### ISSUE THREAD

**Issue by mvanbrab** [Informatievlaanderen/OSLOthema-perceel#14]
De definitie van Ontwikkelbare Bedrijvenzone "Een Ontwikkelbare Bedrijvenzone bevat de contouren van de Bedrijventerreinen.. " doet vermoeden dat de richting van de associatie "is deel van", die nu van Ontwikkelbare Bedrijvenzone naar Bedrijventerrein loopt, verkeerd is.

Is dit zo?

**Comment by mvanbrab** [comment]
Aangezien de definitie van deze "is deel van" associatie in het applicatieprofiel duidelijk is, is het allicht de definitie van Ontwikkelbare Bedrijvenzone zelf die dubieus is.

**Comment by bertvannuffelen** [comment]
@bertvannuffelen : te bespreken + de cardinaliteiten geven ook tegenstrijdige informatie.

**Comment by mvanbrab** [comment]
De gewijzigde definitie (zie #18) klopt nu wel met de richting van de pijl. Rest nog opmerking van @bertvannuffelen  over de kardinaliteiten.

**Comment by bertvannuffelen** [comment]
opgenomen in specificatie
