### ISSUE TITLE
Richting "is gerelateerd aan" tussen BedrijventerreinGebruiksperceel en OntwikkelbareBedrijvenzone? 

### ISSUE THREAD

**Issue by mvanbrab** [Informatievlaanderen/OSLOthema-perceel#15]
![afbeelding](https://user-images.githubusercontent.com/6448245/74838467-efc75400-5323-11ea-88ba-928fc6688ab3.png)

In dit geval is de specificatie correct (*), maar de pijl staat in de verkeerde richting op het diagram.

De richting van de pijl aanpassen, met behoud van de huidige spec is mogelijk (technisch issue...).
Deze issue om te checken of dit de bedoeling wel is.

(*) De eigenschap "is gerelateerd aan" komt voor in de entiteit BedrijventerreinGebruiksperceel en heeft als beschrijving "Ontwikkelbare bedrijvenzone waarmee het bedrijventerreingebruiksperceel kan geassocieerd worden."

**Comment by bertvannuffelen** [comment]
@bertvannuffelen : nakijken

**Comment by mvanbrab** [comment]
De voorgestelde oplossing/aanpassing (die dus nog na te kijken is, @bertvannuffelen) is vanaf nu zichtbaar in de specificaties:
* https://otl-test.data.vlaanderen.be/doc/vocabularium/bedrijventerrein/tijdens-aanpassingen-kandidaat-standaard
* https://otl-test.data.vlaanderen.be/doc/applicatieprofiel/bedrijventerrein/tijdens-aanpassingen-kandidaat-standaard

**Comment by bertvannuffelen** [comment]
cardinaliteiten zijn beide 0..*

richting van Ontwikkelbare bedrijvenzone naar Bedrijventerreinperceel maken

om aan te geven wat de specifieke blokeringsoorzaken zijn.

**Comment by mvanbrab** [comment]
Update gedaan en zichtbaar op (let op, geen otl- meer in de URLs):
- https://test.data.vlaanderen.be/doc/vocabularium/bedrijventerrein/tijdens-aanpassingen-kandidaat-standaard
- https://test.data.vlaanderen.be/doc/applicatieprofiel/bedrijventerrein/tijdens-aanpassingen-kandidaat-standaard

**Comment by bertvannuffelen** [comment]
opgenomen in specificatie
