### ISSUE TITLE
Richting "is gerelateerd aan" tussen EconomischGebied en Bedrijventerrein?

### ISSUE THREAD

**Issue by mvanbrab** [Informatievlaanderen/OSLOthema-perceel#16]
![afbeelding](https://user-images.githubusercontent.com/6448245/74840817-f061e980-5327-11ea-9025-f384dd320831.png)

In dit geval is de specificatie verkeerd (*), alhoewel de pijl in de juiste richting staat op het diagram.

Aanpassen van de spec, met behoud van huidige richting van de pijl is mogelijk (technisch issue...).
Deze issue om te checken of dit de bedoeling wel is.

(*) de eigenschap "is gerelateerd aan" komt voor in de entiteit EconomischGebied maar heeft de beschrijving "Economisch Gebied waarmee het bedrijventerrein kan geassocieerd worden.", die eerder van toepassing lijkt voor een eigenschap in de entiteit Bedrijventerrein. Correctie bestaat er dus in deze eigenschap te verplaatsen naar Bedrijventerrein, zij het met een gewijzigde naam "is gerelateerd aan economisch gebied", omdat Bedrijventerrein al een eigenschap "is gerelateerd aan" heeft, die betrekking heeft op een Planningzone.

**Comment by mvanbrab** [comment]
Voorgestelde aanpassing zichtbaar op https://otl-test.data.vlaanderen.be/doc/applicatieprofiel/bedrijventerrein/tijdens-aanpassingen-kandidaat-standaard

**Comment by mvanbrab** [comment]
De voorgestelde oplossing/aanpassing is vanaf nu zichtbaar in de specificaties:
* https://otl-test.data.vlaanderen.be/doc/vocabularium/bedrijventerrein/tijdens-aanpassingen-kandidaat-standaard
* https://otl-test.data.vlaanderen.be/doc/applicatieprofiel/bedrijventerrein/tijdens-aanpassingen-kandidaat-standaard

**Comment by bertvannuffelen** [comment]
cardinaliteit moet wel 0..1 zijn (optioneel)

**Comment by mvanbrab** [comment]
Update gedaan en zichtbaar op (let op, geen otl- meer in de URLs):
- https://test.data.vlaanderen.be/doc/vocabularium/bedrijventerrein/tijdens-aanpassingen-kandidaat-standaard
- https://test.data.vlaanderen.be/doc/applicatieprofiel/bedrijventerrein/tijdens-aanpassingen-kandidaat-standaard

**Comment by bertvannuffelen** [comment]
opgenomen in specificatie
