### ISSUE TITLE
In Bedrijventerrein: niet toegelaten uitbreiding van namespace https://data.vlaanderen.be/ns/generiek# met https://data.vlaanderen.be/ns/generiek#contactinfo

### ISSUE THREAD

**Issue by mvanbrab** [Informatievlaanderen/OSLOthema-perceel#17]
OSLO-Generiek::Agent heeft hier een attribuut contactinfo gekregen (dat automatisch de uri https://data.vlaanderen.be/ns/generiek#contactinfo creëert, maar die uri is niet gedefinieerd in OSLO-Generiek). Dat mag dus niet niet.

Mogelijke oplossing:
Behoud attribuut contactinfo in OSLO-Generiek::Agent, maar forceer de uri met een tag uri =  http://schema.org/contactPoint.

**Comment by mvanbrab** [comment]
Voorgestelde aanpassing zichtbaar op https://otl-test.data.vlaanderen.be/doc/applicatieprofiel/bedrijventerrein/tijdens-aanpassingen-kandidaat-standaard

**Comment by mvanbrab** [comment]
De voorgestelde oplossing/aanpassing is vanaf nu zichtbaar in de specificatie:
* https://otl-test.data.vlaanderen.be/doc/applicatieprofiel/bedrijventerrein/tijdens-aanpassingen-kandidaat-standaard

**Comment by bertvannuffelen** [comment]
opgenomen in specificatie
