### ISSUE TITLE
Verzorg de definities

### ISSUE THREAD

**Issue by mvanbrab** [Informatievlaanderen/OSLOthema-perceel#18]
Sommige definities zijn niet genoeg verzorgd.
Best eens de hele lijst overlopen (voor beide vocabularia en beide applicatieprofielen).

Enkele voorbeelden (dit is geen limitatieve lijst):

- Eigenschap default (in Ruimtelijke Eenheid Geometrie)
"**Geometrie die moet worden gebruikt bv bij voorstelling op kaart.**" 
Deze definitie is onduidelijk, zeker bij een eigenschap met verwachte type Boolean.
Bovendien gebruikt ze een voorbeeld. Voorbeelden kunnen beter los van een sluitende definitie verhuizen naar "Gebruik".

- Eigenschap dimensie (in Ruimtelijke Eenheid)
"**De dimensie van de ruimtelijke eenheid.**"
Deze definitie is circulair.

- Zakelijk Recht
"**De zakelijke rechten zijn rechten die rechtstreeks op een zaak worden uitgeoefend. Een zakelijk recht geef aan zijn titularis een rechtstreekse en onmiddellijke macht over de zaak waarop het is gevestigd. Een zakelijk recht is een absoluut recht, in die zin dat zijn titularis het tegen iedereen kan doen gelden.**"
Deze definitie begint met een herhaling van het begrip zelf, bevat overbodige informatie die beter in "Gebruik" kan staan en is niet aangepast aan de context van het model:
Kan misschien beter zo:
"**Recht dat aan de betrokken agent een rechtstreekse en onmiddellijke macht geeft op het betrokken kadastraal patrimoniumperceel.**"
Terwijl de nota "Gebruik" in dit geval zou kunnen worden uitgebreid naar:
"**Deze definitie is gealigneerd met de definitie van de Algemene Administratie van de PatrimoniumDocumentatie (AAPD).
'De zakelijke rechten zijn rechten die rechtstreeks op een zaak worden uitgeoefend. Een zakelijk recht geeft aan zijn titularis een rechtstreekse en onmiddellijke macht over de zaak waarop het is gevestigd. Een zakelijk recht is een absoluut recht, in die zin dat zijn titularis het tegen iedereen kan doen gelden.'**"

- Eigenschap beperking (in Bedrijventerreinperceel)
"**Deze eigenschap geeft aan welke de mogelijk beperking een bepaald bedrijventerreinperceel momenteel ondervindt.**"
Deze definitie bevat taalfouten (en zo zijn er nog vele met taalfouten en/of typo's).

**Ter informatie: de modelleringsregels https://github.com/Informatievlaanderen/OSLO-handleiding/blob/master/Modellering/OSLO-Modelleringsregels.pdf bevatten richtlijnen voor definities.**
Deze issue verwijst voornamelijk naar de volgende;
"
REGEL: Gebruik geen circulaire beschrijvingen.
Bv niet: een PubliekeOrganisatie is een organisatie die publiek is.
REGEL: Begin een definitie niet met het herhalen vd naam vh concept.
Bv voor Adres: “Een Adres is informatie die toelaat om…” moet zijn “Informatie die toelaat om…”.
REGEL: Een definitie is een samenvattende omschrijving, zorg dat ze geen voorbeelden of bijkomende uitleg bevat.
Aanvullende omschrijvingen worden gegeven in de tag usageNote, zie §3.2.19.
"

**Comment by IdrisPeiren** [comment]
Even de cursus zakelijk recht boven gehaald: het burgerlijk wetboek geeft geen definitie. Voorstel gebaseerd op deze cursus en aangepast aan de context:
Verleent aan de agent een recht van genot op het kadastraal patrimoniumperceel, inclusief een recht op de vruchten, eventueel het recht om over het kadastraal patrimoniumperceel te beschikken en heeft betrekking op het kadastraal patrimoniumperceel zelf.

**Comment by IdrisPeiren** [comment]
Bedrijventerreinperceel
Een Bedrijventerreingebruiksperceel is een ruimtelijke eenheid binnen een Bedrijventerrein met eenzelfde gebruik of functie.
Moet worden:
Een ruimtelijke eenheid binnen een Bedrijventerrein met eenzelfde gebruik, functie of eigenaar.

**Comment by IdrisPeiren** [comment]
Functie:
De functie geeft de (verschillende) functies aan die men kan terugvinden op het Bedrijventerreingebruiksperceel en het percentage van het gebruiksperceel dat gedekt wordt door elke functie.
Moet worden:
Geeft de hoofdfunctie aan die men kan terugvinden op het Bedrijventerreinperceel. De hoofdfunctie beslaat 50% of meer van de oppervlakte van het bedrijventerreinperceel.

**Comment by IdrisPeiren** [comment]
inGebruik:
Voorstel om geen boolean te gebruiken maar Ingebruik en NietInGebruik, dus naam wijzigen naar Gebruik?

**Comment by IdrisPeiren** [comment]
Beperking:
Deze eigenschap geeft aan welke de mogelijk beperking een bepaald bedrijventerreingebruiksperceel momenteel ondervindt.
Moet worden:
Deze eigenschap geeft aan welke mogelijke beperking(en) een bepaald bedrijventerreinperceel momenteel ondervindt.

**Comment by IdrisPeiren** [comment]
Ontwikkelbare bedrijvenzone:
Een ontwikkelbare Bedrijvenzone bevat de contouren van de Bedrijventerreinen vanaf de mijlpaal publicatie in het Belgisch Staatsblad tot aan de oplevering van de nutsvoorzieningen en infrastructuur. Deze zones kunnen nieuwe terreinen zijn of herontwikkelingstrajecten. Wanneer een (her)ontwikkeling in meerdere fasen gebeurt, dan wordt de ontwikkelbare zone opgesplitst volgens deze fasen.
Moet worden:
Een (deel van) een Bedrijventerrein vanaf de mijlpaal publicatie in het Belgisch Staatsblad tot aan de oplevering van de nutsvoorzieningen en infrastructuur. Deze zones kunnen nieuwe terreinen zijn of herontwikkelingstrajecten. Wanneer een (her)ontwikkeling in meerdere fasen gebeurt, dan wordt de ontwikkelbare zone opgesplitst volgens deze fasen.

**Comment by IdrisPeiren** [comment]
Homepage:
Adres van de homepage van de website van de ontwikkelbare bedrijvenzone.
Moet worden:
Adres van de homepage van de website van de ontwikkelbare bedrijvenzone of ontwikkelaar

**Comment by IdrisPeiren** [comment]
Voorziene uitgifte:
Het voorziene tijdstip waarop de ontwikkeling van de ontwikkelbare bedrijvenzone voltooid zal zijn.
Moet worden:
Het voorziene tijdstip waarop het eerste Bedrijventerreinperceel binnen een ontwikkelbare zone in verkoop zal gaan.

**Comment by mvanbrab** [comment]
Betreffende "Functie" (commentaar Idris hoger): enkel in implementatiemodel (Bert). De rest in voc, ap (Martin) en im (Bert).

**Comment by mvanbrab** [comment]
De voorgestelde oplossingen/aanpassingen (behalve "Functie", zie vorige comment) zijn vanaf nu zichtbaar in de specificaties:
- https://test.data.vlaanderen.be/doc/vocabularium/perceel/tijdens-aanpassingen-kandidaat-standaard
- https://test.data.vlaanderen.be/doc/applicatieprofiel/perceel/tijdens-aanpassingen-kandidaat-standaard
- https://test.data.vlaanderen.be/doc/vocabularium/bedrijventerrein/tijdens-aanpassingen-kandidaat-standaard 
- https://test.data.vlaanderen.be/doc/applicatieprofiel/bedrijventerrein/tijdens-aanpassingen-kandidaat-standaard

**Comment by bertvannuffelen** [comment]
opgenomen in specificatie
