### ISSUE TITLE
Gebruik van rechttype in plaats van rechtstype, naar analogie van Zakelijkrechttype

### ISSUE THREAD

**Issue by ddvlanck** [Informatievlaanderen/OSLOthema-perceel#2]
Bijkomende vraag: is een zakelijkrechttype een rechttype?

**Comment by KevinHaleydt** [comment]
To do:
Rechtstype zal aangepast worden naar rechttype zodat dit consistent is met de andere types. 

Voor de bijkomende vraag: momenteel zijn er in dit applicatieprofiel geen codelijsten bepaald.

**Comment by mvanbrab** [comment]
De voorgestelde oplossing/aanpassing is vanaf nu zichtbaar in de specificaties:
* https://otl-test.data.vlaanderen.be/doc/vocabularium/bedrijventerrein/tijdens-aanpassingen-kandidaat-standaard
* https://otl-test.data.vlaanderen.be/doc/applicatieprofiel/bedrijventerrein/tijdens-aanpassingen-kandidaat-standaard

**Comment by bertvannuffelen** [comment]
opgenomen in specificatie
