### ISSUE TITLE
Subsidietype schrappen

### ISSUE THREAD

**Issue by IdrisPeiren** [Informatievlaanderen/OSLOthema-perceel#21]
Subsidietype mag geschrapt worden als eigenschap van de klasse beheerde bedrijvenzone. Deze informatie zit bij VLAIO en zal afgeleid worden uit de digitale indiening van subsidiedossiers.

**Comment by bertvannuffelen** [comment]
Dit is voor het implementatiemodel van toepassing.

**Comment by bertvannuffelen** [comment]
toch toegepast in de finale versie van de erkende standaard.
