### ISSUE TITLE
Lijst technische aanpassingen OSLO-Perceel voc+ap en OSLO-Bedrijventerrein voc + ap

### ISSUE THREAD

**Issue by mvanbrab** [Informatievlaanderen/OSLOthema-perceel#3]
**In dit self-assigned issue houd ik bij wat ik zie en corrigeer (technische aanpassingen) op branch 
aanpassingen-kandidaat-standaard (voorlopig nog op een fork).**
Deze lijst uitbreiden in plaats van afzonderlijke issues te maken.
[OK] ervoor plaatsen als aanpassing gebeurd is.

**OSLO-Perceel vocabularium ---------------------------------------------------------**

* [OK] BaseURI van OSLO-Perceel moet https:// zijn.

* [OK] Ook properties met hardcoded URI http://data.vlaanderen.be/ns/perceel#... aanpassen. Beter name tag gebruiken in plaats van uri tag. Komt voor bij 5 attributen. Name tags na correctie:
  * Recht.type
  * Restrictie.type
  * RuimtelijkeEenheid.type
  * Verantwoordelijkheid.type
  * ZakelijkRecht.type

* [OK] Op bovenstaande properties onterechte tags domain = rdfs:Resource verwijderen (elke eigenschap heeft zijn eigen uri en zijn eigen specifiek domein).

* [OK] Op bovenstaande properties de waarde van tag ap-definition-nl overnemen in tag definition-nl (de oorspronkelijke definition-nl  is te generiek "De aard van een resource.".

* [OK] Restrictie.restrictietype: het dubbele label-nl ("Restrictietype") verwijderen.

* [OK] Voor de 4 eigenschappen "aandeel" is het bereik (of in AP het verwacht type) leeg. Oorzaak: float niet ondersteund door toolchain. Oplossing: wijzigen in Double.

* [OK] Enumeraties correcte uri van skos:Concept geven

* [OK] Eigenschap identificator (2*) de uri meegeven http://www.w3.org/ns/adms#identifier; de waarde van tag ap-definition-nl overnemen in tag definition-nl

* [OK] Eigenschappen in verschillende klassen die dezelfde (berekende) uri kregen, maar een verschillend bereik hebben een unieke uri geven (door middel van een name tag met klasse prefix) en de waarde van tag ap-definition-nl overnemen in tag definition-nl. Te behandelen:
  * geometrie (2*)
  * oppervlakte (2*)

* [OK] Eigenschappen in verschillende klassen die dezelfde berekende uri krijgen en ook hetzelfde bereik hebben (behalve skos:Concept) veralgemenen. Doe dit door op alle instanties een tag domain=http://www.w3.org/2000/01/rdf-schema#Resource te zetten. Zet overal tag ignore=true in VOC, behalve op één instance. Te behandelen:
  * aandeel (4*)
  * datumbijwerking (2*)
  * geldigheidsperiode (5*) (in RuimtelijkeEenheid, aanpassen tag domain https://www.w3.org/2000/01/rdf-schema#Resource --> http://www.w3.org/2000/01/rdf-schema#Resource)

* [OK] Correcties op associaties met associatieklasse:
  * lijst:
    * heeftRestrictie
    * heeftVerantwoordelijkheid
    * heeftRecht
    * heeftZakelijkRecht
  * weglaten: tag ignore=true
  * toevoegen: tag package=OSLO-Perceel
    * om dit te laten werken oude package OSLO-Perceel onder OSLO²_vocabularium hernoemen naar OSLO-PerceelOud (anders foutmelding; zie report file)
  * aanpassen (ap-)label-nl naar afzonderlijke woorden met spaties

* [OK] Consequentie in label.nl tags (scheiden met spaties; hoofdletter / kleine letter):
  * "identificator" (2*) (kleine i)
  * "landgebruik" (kleine l)
  * "is gerelateerd aan" (2 associaties)
  * "Ruimtelijke Eenheid Geometrie"
  * "Ruimtelijke Eenheid Oppervlakte"
  * "datum bijwerking" (2*)
  * "officiële oppervlakte"
  * "type (Ruimtelijke Eenheid)"
  * "type (Zakelijk Recht)"

* [OK] Consequentie in UML namen
  * "isGerelateerdAan"
  * "ligtOp"

* [OK] Rare karakters in UML namen en daaruit volgende uri's vermijden
  * "officiëleOppervlakte" --> "officieleOppervlakte"

* [OK] Weglaten verwarrende overbodige klassen in package OSLO-Perceel
  * "Gebouw_child"
  * "OSLO-Gebouw::Gebouw"
  * "OSLO-Generiek::Agent"

* [OK] Hernoem package OSLO-Generiek (deze met diagram OSLO-Generiek) naar OSLO-GeneriekVoc!!! (om te zien welke elementen op het diagram uit dit package komen)

* [OK] Vervang op het diagram van OSLO-Perceel volgende elementen die uit het package OSLO-GeneriekVoc!!! komen door gelijknamige elementen uit het package OSLO-Generiek (deze met het diagram OSLO-GeneriekBasis)
  * Agent
  * Periode
  * Geometrie
  * GeometrieMethodeWaarde

* [OK] Corrigeer Identificator: property met naam "gestructureerdedentificator (I ontbreekt)

* [OK] Verwijder uit het diagram van OSLO-Perceel volgende elementen
  * GetypeerdeString (uit OSLO-Generiek, wegens geen toegevoegde waarde: alle attributen zijn toch ignore=true)

* [OK] Voeg ter volledigheid volgende elementen toe uit package OSLO-Generiek:
  * StandaardEenheid
  * Getal

* [OK] Herlink alle types van toepassing naar deze die voorkomen in package OSLO-Generiek
  * Periode (5*)
  * Identificator (2*)
  * Geometrie
  * GeometrieMethodeWaarde
  * KwantitatieveWaarde

* [OK] KadastraalPatrimoniumperceel
  * afleiden van OSLO-Generiek::Object
  * eigenschap identificator verwijderen (wordt in AP afgedaald uit OSLO-Generiek::Object)

* [OK] De vier associaties met associatieklasse, waarbij Agent betrokken is aanpassen, met rollen (in de omgekeerde richting t.o.v. vroegere pijlen)
  * associatie heeftZakelijkRecht:
    * rol toevoegen aan SOURCE kant met UML naam agentMetZakelijkRecht
    * op overeenkomstige Connector Source tags toevoegen: label-nl, definition-nl, package = OSLO-Perceel
    * associatie: richtingspijl verwijderen (Directon: No Indicator), UML naam verwijderen, label-nl en definition-nl verwijderen (package laten staan)
  * associatie heeftRestrictie:
    * rol toevoegen aan SOURCE kant met UML naam agentMetRestrictie
    * op overeenkomstige Connector Source tags toevoegen: label-nl, definition-nl, package = OSLO-Perceel
    * associatie: richtingspijl verwijderen (Directon: No Indicator), UML naam verwijderen, label-nl en definition-nl verwijderen (package laten staan)
  * associatie heeftVerantwoordelijkheid:
    * rol toevoegen aan SOURCE kant met UML naam agentMetVerantwoordelijkheid
    * op overeenkomstige Connector Source tags toevoegen: label-nl, definition-nl, package = OSLO-Perceel
    * associatie: richtingspijl verwijderen (Directon: No Indicator), UML naam verwijderen, label-nl en definition-nl verwijderen (package laten staan)
  * associatie heeftRecht:
    * rol toevoegen aan SOURCE kant met UML naam agentMetRecht
    * op overeenkomstige Connector Source tags toevoegen: label-nl, definition-nl, package = OSLO-Perceel
    * associatie heeftRecht: richtingspijl verwijderen (Directon: No Indicator), UML naam verwijderen, label-nl en definition-nl verwijderen (package laten staan)

* [OK] Hernoemen rechtstype naar rechttype
  * UML naam rechtstype (in Recht): aanpassen naar rechttype
  * UML naam van Rechtstype (enum): aanpassen naar Rechttype

* [OK] Afsplitsen in apart bestand OSLO-Perceel-VOC.eap

* [OK] Toevoeging stakeholders aan de spec

* [OK] Aanpassen ap-usageNote-nl voor Kadastraal Patrimoniumperceel

* [OK] Aanpassen usageNote-nl en ap-usageNote-nl voor Kadastraal Planperceel

**OSLO-Perceel applicatieprofiel ---------------------------------------------------------**

* [OK] Alle updates zie vocabularium OSLO-Perceel. Naast technische aanpassingen geeft dit als gevolg voor het applicatieprofiel:
  * In de associatieklassen (Recht, Restrictie, Verantwoordelijkheid, ZakelijkRecht) zijn de attributen zichtbaar die linken naar de deelnemende klassen aan associatie 

* [OK] Na afsplitsing vocabularium OSLO-Perceel naar afzonderlijke .eap: verwijder tag ignore=true op volgende attributen. Dit brengt het applicatieprofiel weer comform de oorspronkelijke versie wat deze attributen betreft.
  * aandeel (3*)
  * datumbijwerking (1*)
  * geldigheidsperiode (4*)

* [OK] KadastraalPatrimoniumperceel
  * afleiden van OSLO-Generiek::Object
  * eigenschap identificator: UML naam wijzigen in ^identificator om aan te duiden dat deze uit OSLO-Generiek::Object werd geërfd

* [OK] Hernoem het diagram naar OSLO-PerceelApplicatieprofiel

* [OK] Toevoeging stakeholders aan de spec

**OSLO-Bedrijventerrein vocabularium ---------------------------------------------------------**

* [OK] Synchroniseer in de kopie van het vocabularium OSLO-Perceel alle aanpassingen zoals beschreven voor dit vocabularium, behalve: geen tag ignore=true op volgende attributen:
  * aandeel (3*)
  * datumbijwerking (1*)
  * geldigheidsperiode (4*)

* [OK] Correct gebruik van associaties met associatieklassen Recht en Verantwoordelijkheid (uit package OSLO-Perceel!), met als gevolg:
  * Correcte uri's
  * Toevoeging in de associatieklassen van linkende attributen naar deelnemened klassen
  * correcte kardinaliteiten in het applicatieprofiel

* [OK] Toevoeging stakeholders aan de spec

* [OK] Consequentie in label.nl tags (scheiden met spaties; hoofdletter / kleine letter):
  * "Bedrijventerreingebruiksperceel"
  * "beschikbare kavels" (in Bedrijventerrein)
  * "beschikbare oppervlakte" (in Bedrijventerrein)
  * "commerciële naam" (in Bedrijventerrein)
  * "datum schorsing" (in SchorsingInfo)
  * "dominante economische activiteit" (in EconomischGebied)
  * "Functiewaarde" (het datatype)
  * "link schorsing" (in SchorsingInfo)
  * "naam" (in OntwikkelbareBedrijvenzone")
  * "schorsing opmerking" (in SchorsingInfo)
  * "status ontwikkeling" (in OntwikkelbareBedrijvenzone)
  * "stedenbouwkundige voorschriften" (in Plan)
  * "voorziene uitgifte" (in OntwikkelbareBedrijvenzone)

* [OK] Vermijden verwarring FunctieWaarde (datatype), vs. Functiewaarde (enum):
  * enum: UML naam "Functietype"
  * datatype:
    * UML naam "Functiewaarde"
    * label-nl "Functiewaarde"
  * eigenschap functie (in BedrijventerreinGebruiksperceel) moet als type krijgen het datatype (nu genaamd "Functiewaarde" en niet de enum) * controleer het bereik (is dus niet skos:Concept)
  * eigenschap functietype (in Functiewaarde), definitie aanpassen "Aanduiding van het functietype"

* [OK] Eigenschap identificator (in Plan)
  * uri meegeven http://www.w3.org/ns/adms#identifier
  * definition-nl overnemen uit ap-definition-nl

* [OK] Enumeraties correcte uri van skos:Concept geven (opgelet, ook op OSLO-Perceel::RuimtelijkeEenheidtype)

* [OK] URI niet toekennen met uri tag:
  * Functiewaarde.functietype: verwijder tag uri (automatische uri is OK)
  * BeheerdeBedrijvenzone.subsidietype: verwijder tag uri (automatische uri is OK)

* [OK] Rare karakters in UML namen en daaruit volgende uri's vermijden
  * "commerciëleNaam" --> "commercieleNaam"

* [OK] "is deel van" tussen Beheerde Bedrijvenzone en Bedrijventerrein: uri toekennen (zelfde als op andere "is deel van" associaties)

* [OK] functietype (in Functiewaarde): tag domain verwijderen

* [OK] Hernoem package OSLO-Generiek (deze met diagram OSLO-Generiek) naar OSLO-GeneriekVoc!!! (om te zien welke elementen op het diagram uit dit package komen)

* [OK] Vervang op het diagram van OSLO-Bedrijventerrein volgende elementen die uit het package OSLO-GeneriekVoc!!! komen door gelijknamige elementen uit het package OSLO-Generiek (deze met het diagram OSLO-GeneriekBasis)
  * Identificator - oops, hier zit een foutje in, property met naam "gestructureerdedentificator (I ontbreekt)

* [OK] Verwijder uit het diagram van OSLO-Bedrijventerrein volgende elementen
  * TaalString (uit OSLO-GeneriekVoc!!!, wegens geen toegevoegde waarde: alle attributen zijn toch ignore=true)
* Voeg ter volledigheid volgende elementen toe uit package OSLO-Generiek:
  * GestructureerdeIdentificator
  * StandaardEenheid
  * Getal

* [OK] Herlink alle types van toepassing naar deze die voorkomen in package OSLO-Generiek
  * ContactInfo
  * Periode
  * Identificator
  * TaalString (5*)
  * KwantitatieveWaarde (2*)
  * Geometrie

* [OK] Kardinaliteit van beperking (in Bedrijventerreinperceel) aanpassen naar [0..*]

* [OK] Eigenschap voorzieneUitgifte in OntwikkelbareBedrijvenzone: type aanpassen naar Date 

* [OK] Klassenaam BedrijventerreinGebruiksperceel wijzigen naar Bedrijventerreinperceel. Ook aanpassen:
  * label-nl
  * definition-nl
  * na zoeken in spec ook:
  * definition-nl van alle properties in Bedrijventerreingperceel
  * definition-nl van Functiewaarde
  * definition-nl van Functiewaarde.percentage
  * definition-nl van Bedrijventerrein

* [OK] Afsplitsen in apart bestand OSLO-Bedrijventerrein-VOC.eap

**OSLO-Bedrijventerrein applicatieprofiel ---------------------------------------------------------**

* [OK] Alle updates zie OSLO-Bedrijventerrein vocabularium

* [OK] Toevoeging stakeholders aan de spec

* [OK] Associatie isGerelateerdAan tussen BedrijventerreinGebruiksperceel en OntwikkelbareBedrijvenzone: de spec. klopt, gelet op de definitie die gegeven is aan de eigenschap "is gerelateerd aan" (in BedrijventerreingGebruiksprofiel), maar de pijl wijst in de verkeerde ricthing. Richting pijl aanpassen naar "to Destination". Wegens toolchain issue https://github.com/Informatievlaanderen/Data.Vlaanderen.be/issues/320 is dit in dit geval enkel een visuele correctie. Issue voor maken zodat men kan controleren.

* [OK] Associatie isGerelateerdAan tussen EconomischGebied en Bedrijventerrein: de spec. klopt niet, gelet op de definitie die gegeven is aan de eigenschap "is gerelateerd aan" (die dus onterecht in de entiteit EconomischGebied staat, terwijl ze in Bedrijventerrein zou moeten staan). Is eveneens te wijten aan toolchain issue https://github.com/Informatievlaanderen/Data.Vlaanderen.be/issues/320. Als volgt aanpassen en issue voor maken zodat men kan controleren.
  * Associatie omkeren zodat Bedrijventerrein SOURCE wordt. Let op, kardinaliteiten aanpassen zoals figuur was. De richting van de pijl aanpassen naar "to Destination", zodat deze weer zoals voorheen in de figuur staat.
  * uri tag weggooien (twee attributen met zelfde uri binnen één klasse Bedrijventerrein kunnen niet, en er was er al eentje richting Planningzone)
  * UML naam aanpassen naar "isGerelateerdAanEconomischGebied"
  * label-nl aanpassen naar "is gerelateerd aan economisch gebied"
  * definition-nl overnemen uit ap-definition-nl

* [OK] Eigenschap contactinfo in Agent: tag toevoegen uri = https://data.vlaanderen.be/ns/generiek#contactinfo

* [OK] Hernoem het diagram naar OSLO-BedrijventerreinApplicatieprofiel

**Comment by bertvannuffelen** [comment]
opgenomen in specificatie
