### ISSUE TITLE
hernoeming klasse naam BedrijventerreinGebruiksperceel -> Bedrijventerreinperceel

### ISSUE THREAD

**Issue by bertvannuffelen** [Informatievlaanderen/OSLOthema-perceel#4]
suggestie om BedrijventerreinGebruiksperceel te hernoemen naar Bedrijventerreinperceel

URI: 
https://data.vlaanderen.be/ns/bedrijventerrein#BedrijventerreinGebruiksperceel
In applicatieprofiel:
https://data.vlaanderen.be/doc/applicatieprofiel/bedrijventerrein/#BedrijventerreinGebruiksperceel

**Comment by mvanbrab** [comment]
Ter info: indien aanvaard, ook verwijzing ernaartoe ("gebruikdsperceel") in definitie van Bedrijventerrein aanpassen.

**Comment by mvanbrab** [comment]
De voorgestelde oplossing/aanpassing is vanaf nu zichtbaar in de specificaties:
* https://otl-test.data.vlaanderen.be/doc/vocabularium/bedrijventerrein/tijdens-aanpassingen-kandidaat-standaard
* https://otl-test.data.vlaanderen.be/doc/applicatieprofiel/bedrijventerrein/tijdens-aanpassingen-kandidaat-standaard

**Comment by bertvannuffelen** [comment]
opgenomen in specificatie
