### ISSUE TITLE
typering xsd:datetime->xsd:date voor  eigenschap voorzieneUitgifte

### ISSUE THREAD

**Issue by bertvannuffelen** [Informatievlaanderen/OSLOthema-perceel#5]
Een datetime voor een toekomstige realisatie is heel erg precies. Daarom is een datum meer realistisch.

URI:
https://data.vlaanderen.be/ns/bedrijventerrein#voorzieneUitgifte

applicatieprofiel:
https://data.vlaanderen.be/doc/applicatieprofiel/bedrijventerrein/#Ontwikkelbare%20Bedrijvenzone%3AvoorzieneUitgifte

**Comment by mvanbrab** [comment]
De voorgestelde oplossing/aanpassing is vanaf nu zichtbaar in de specificaties:
* https://otl-test.data.vlaanderen.be/doc/vocabularium/bedrijventerrein/tijdens-aanpassingen-kandidaat-standaard
* https://otl-test.data.vlaanderen.be/doc/applicatieprofiel/bedrijventerrein/tijdens-aanpassingen-kandidaat-standaard

**Comment by bertvannuffelen** [comment]
opgenomen in specificatie
