### ISSUE TITLE
open issues in OSLO-Discussion

### ISSUE THREAD

**Issue by bertvannuffelen** [Informatievlaanderen/OSLOthema-perceel#6]
De volgende issues moeten ook bekeken worden

https://github.com/Informatievlaanderen/OSLO-Discussion/issues?q=is%3Aissue+is%3Aopen+label%3APerceel

**Comment by mvanbrab** [comment]
Voor al deze issues is een voorgestelde oplossing/aanpassing vanaf nu zichtbaar in de specificaties:
* https://otl-test.data.vlaanderen.be/doc/vocabularium/perceel/tijdens-aanpassingen-kandidaat-standaard
* https://otl-test.data.vlaanderen.be/doc/applicatieprofiel/perceel/tijdens-aanpassingen-kandidaat-standaard
* https://otl-test.data.vlaanderen.be/doc/vocabularium/bedrijventerrein/tijdens-aanpassingen-kandidaat-standaard
* https://otl-test.data.vlaanderen.be/doc/applicatieprofiel/bedrijventerrein/tijdens-aanpassingen-kandidaat-standaard
