### ISSUE TITLE
directionaliteit heeftVerantwoordelijkheid

### ISSUE THREAD

**Issue by bertvannuffelen** [Informatievlaanderen/OSLOthema-perceel#7]
In het model is de directionaliteit is van de Agent naar de ruimtelijkeEenheid gezet. Echter de natuurlijke setting is van de ruimtelijkeEenheid naar de Agent.

**Comment by mvanbrab** [comment]
Bij deze gelegenheid eens nadenken over de namen (en de definities!) van de drie associaties tussen OSLO-Generiek::Agent en OSLO-Perceel::RuimtelijkeEenheid en van de associatie tussen OSLO-Generiek::Agent en KadastraalPatrimoniumperceel: 
- heeftVerantwoordelijkheid
- heeftRecht
- heeftRestrictie
- heeftZakelijkRecht

Het betreft drie associaties die gepaard gaan met een associatieklasse:
- Verantwoordelijkheid
- Recht
- Restrictie
- ZakelijkRecht

De naamgeving heeftVerantwoordelijkheid (etc.) laat vermoeden dat de range Verantwoordelijkheid (etc.) zou zijn, maar dat is niet zo (ongeacht de ter discussie gestelde richting van de associatie).

Suggestie: alle richtingen omdraaien en naamsverwarring vermijden door over te schakelen van benoemde associaties naar rollen op onbenoemde associaties

**Comment by mvanbrab** [comment]
De voorgestelde oplossing/aanpassing is vanaf nu zichtbaar in de specificaties:
* https://otl-test.data.vlaanderen.be/doc/vocabularium/perceel/tijdens-aanpassingen-kandidaat-standaard
* https://otl-test.data.vlaanderen.be/doc/applicatieprofiel/perceel/tijdens-aanpassingen-kandidaat-standaard
* https://otl-test.data.vlaanderen.be/doc/vocabularium/bedrijventerrein/tijdens-aanpassingen-kandidaat-standaard
* https://otl-test.data.vlaanderen.be/doc/applicatieprofiel/bedrijventerrein/tijdens-aanpassingen-kandidaat-standaard

**Comment by bertvannuffelen** [comment]
opgenomen in specificatie
