### ISSUE TITLE
max-cardinaliteit beperking moet n zijn

### ISSUE THREAD

**Issue by bertvannuffelen** [Informatievlaanderen/OSLOthema-perceel#8]
In het applicatieprofiel bedrijventerrein moet de max-cardinaliteit voor
https://data.vlaanderen.be/doc/applicatieprofiel/bedrijventerrein/#BedrijventerreinGebruiksperceel%3Abeperking
n zijn

(meerdere opties zijn toegelaten)

**Comment by mvanbrab** [comment]
De voorgestelde oplossing/aanpassing is vanaf nu zichtbaar in de specificatie:
* https://otl-test.data.vlaanderen.be/doc/applicatieprofiel/bedrijventerrein/tijdens-aanpassingen-kandidaat-standaard

**Comment by bertvannuffelen** [comment]
opgenomen in specificatie
